"""Handwritten SQL syntax and read-only semantic binding package."""

from .binder import (
    BoundDelete,
    BoundIndexCondition,
    BoundIndexMutation,
    BoundInsert,
    BoundJoinKey,
    BoundOrderItem,
    BoundPredicate,
    BoundProjectionItem,
    BoundRelation,
    BoundSelect,
    bind_delete,
    bind_insert,
    bind_select,
    bind_statement,
)
from .environment import QueryEnvironment, RegisteredIndex

from .errors import (
    SqlBindingError,
    SqlLexicalError,
    SqlLimitError,
    SqlQueryError,
    SqlSyntaxError,
    SqlUnknownColumnError,
    SqlUnknownTableError,
    SqlUnsupportedError,
)
from .parser import parse_sql
from .planner import (
    DeletePlanSpec,
    FilterSpec,
    IndexScanSpec,
    InsertPlanSpec,
    PhysicalPlanSpec,
    PlanCapabilities,
    PlanSpecDescriptor,
    ProjectionSpec,
    SelectPlanSpec,
    StalePlanError,
    TableScanSpec,
    build_select_plan,
    prepare_plan,
    prepare_select_plan,
)

__all__ = [
    "BoundDelete",
    "BoundIndexCondition",
    "BoundIndexMutation",
    "BoundInsert",
    "BoundJoinKey",
    "BoundOrderItem",
    "BoundPredicate",
    "BoundProjectionItem",
    "BoundRelation",
    "BoundSelect",
    "DeletePlanSpec",
    "FilterSpec",
    "IndexScanSpec",
    "InsertPlanSpec",
    "PhysicalPlanSpec",
    "PlanCapabilities",
    "PlanSpecDescriptor",
    "ProjectionSpec",
    "QueryEnvironment",
    "RegisteredIndex",
    "SelectPlanSpec",
    "SqlBindingError",
    "SqlLexicalError",
    "SqlLimitError",
    "SqlQueryError",
    "SqlSyntaxError",
    "SqlUnknownColumnError",
    "SqlUnknownTableError",
    "SqlUnsupportedError",
    "StalePlanError",
    "TableScanSpec",
    "bind_delete",
    "bind_insert",
    "bind_select",
    "bind_statement",
    "build_select_plan",
    "parse_sql",
    "prepare_plan",
    "prepare_select_plan",
]
