"""Physical relational operators, execution resources, and the row contract."""

from engine.operators.aggregation import (
    Aggregate,
    build_grouped_layout,
    Avg,
    BoundAggregate,
    Count,
    CountColumn,
    ExternalHashGroup,
    HashGroupKernel,
    HashGroupMetrics,
    Max,
    Min,
    Sum,
)
from engine.operators.index_strategies import (
    IndexGroupMetrics,
    IndexJoinMetrics,
    IndexNestedLoopJoin,
    IndexOrderedGroup,
)
from engine.operators.join import (
    GraceHashJoin,
    GraceHashJoinMetrics,
    HashJoinKernel,
    JoinKey,
    JoinSpec,
    NestedLoopJoin,
    NestedLoopMetrics,
    RowSpool,
)
from engine.operators.partitioning import (
    HashPartitioner,
    Partition,
    maximum_partition_count,
    partition_hash,
)
from engine.operators.base import (
    ExecutionOperator,
    Operator,
    OperatorDescriptor,
    OperatorState,
    OperatorStatistics,
    collect,
    execute,
)
from engine.operators.context import (
    DEFAULT_BUDGET_BYTES,
    DEFAULT_MAX_OPEN_HANDLES,
    MINIMUM_BUDGET_BYTES,
    ROW_OVERHEAD_BYTES,
    ExecutionContext,
    HandleLease,
    MemoryReservation,
    ResourceStatistics,
    operator_context,
    row_footprint_bytes,
    value_footprint_bytes,
)
from engine.operators.expressions import (
    And,
    BoundExpression,
    ColumnValue,
    Compare,
    ComparisonOperator,
    Expression,
    Literal,
    Not,
    Or,
    column,
    compare_values,
    data_type_of,
    validate_comparable,
)
from engine.operators.filter import Filter
from engine.operators.pipeline import PhysicalPlan, PlanReport, run_plan
from engine.operators.projection import Projection
from engine.operators.rows import (
    ColumnReference,
    LayoutField,
    RowLayout,
    RowProvenance,
    as_reference,
    validate_identifier,
)
from engine.operators.sorting import (
    DEFAULT_MAX_FAN_IN,
    MINIMUM_FAN_IN,
    MINIMUM_SORT_BUDGET_BYTES,
    BoundSortSpec,
    ExternalSort,
    ExternalSortMetrics,
    SortKey,
    SortSpec,
)
from engine.operators.temp_files import (
    TemporaryWorkspace,
    WorkspaceStatistics,
)
from engine.operators.temp_stream import (
    TemporaryRowReader,
    TemporaryRowWriter,
    TemporaryRun,
)
from engine.operators.scan import (
    EqualitySearch,
    IndexScan,
    index_storage,
    RangeSearch,
    TableScan,
)

# Only classes and functions belong in __all__: the architecture suite resolves
# every exported symbol back to its defining module, which plain int constants
# cannot answer for. They stay importable from engine.operators.context.
__all__ = [
    "Aggregate",
    "And",
    "Avg",
    "BoundAggregate",
    "BoundExpression",
    "BoundSortSpec",
    "ColumnReference",
    "ColumnValue",
    "Compare",
    "ComparisonOperator",
    "Count",
    "CountColumn",
    "EqualitySearch",
    "ExecutionContext",
    "ExecutionOperator",
    "Expression",
    "ExternalHashGroup",
    "ExternalSort",
    "ExternalSortMetrics",
    "Filter",
    "GraceHashJoin",
    "GraceHashJoinMetrics",
    "HandleLease",
    "HashGroupKernel",
    "HashGroupMetrics",
    "HashJoinKernel",
    "HashPartitioner",
    "IndexGroupMetrics",
    "IndexJoinMetrics",
    "IndexNestedLoopJoin",
    "IndexOrderedGroup",
    "IndexScan",
    "JoinKey",
    "JoinSpec",
    "LayoutField",
    "Literal",
    "Max",
    "MemoryReservation",
    "Min",
    "NestedLoopJoin",
    "NestedLoopMetrics",
    "Not",
    "Operator",
    "OperatorDescriptor",
    "OperatorState",
    "OperatorStatistics",
    "Or",
    "Partition",
    "PhysicalPlan",
    "PlanReport",
    "Projection",
    "RangeSearch",
    "ResourceStatistics",
    "RowLayout",
    "RowProvenance",
    "RowSpool",
    "SortKey",
    "SortSpec",
    "Sum",
    "TableScan",
    "TemporaryRowReader",
    "TemporaryRowWriter",
    "TemporaryRun",
    "TemporaryWorkspace",
    "WorkspaceStatistics",
    "as_reference",
    "build_grouped_layout",
    "collect",
    "column",
    "compare_values",
    "data_type_of",
    "execute",
    "index_storage",
    "maximum_partition_count",
    "operator_context",
    "partition_hash",
    "row_footprint_bytes",
    "run_plan",
    "validate_comparable",
    "validate_identifier",
    "value_footprint_bytes",
]
